# Generated by Django 2.2.1 on 2020-05-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_remove_book_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcopy',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
